---
title: "Committees and Advisory Roles"
---
Member of the Academic Review Committee, Indian School of Public Policy, August 2022.

Member of the Board of Advisors, Dvara Trust, (2020-2022).

Member of the Working Group 1 - on the organisational structure and design of the Insolvency & Bankruptcy Board of India, Ministry of Corporate Affairs, June-October 2016

Member of the Options and index committee, NCDEX, (2016-2019).

Member of the Independent Oversight Committee for Product Design, NCDEX, (2015-2019)

Member of the Working Group on Taxation Practices for Financial Instruments in India, RBI, September 2014

Member of the Bankruptcy Laws Reforms Committee, Ministry of Finance, (2014-2016)

Member of the Committee on Data and Information Management in the Reserve Bank of India, RBI, December 2013 to May 2014

Member of the Committee to suggest steps for fulfilling the objectives of price discovery and risk management of Commodity Derivatives Markets, Ministry of Finance, December 2013 to April 2014

Member of the Sub-committee to the Standing Council of experts on the competitiveness of the Indian financial sector, Ministry of Finance, (2013-2016)

Member of Standing Council of experts on the competitiveness of the Indian financial sector, Ministry of Finance, (2013-2016)

Member of the Secondary Markets Advisory Committee, SEBI, (2009-2017)

Member of the Expect Group on Investment guidelines and policy for the New Pension System, PFRDA, October 2008 to January 2009.

Member of the Subcommittee to form guidelines for interest rate futures, of the Technical Advisory Committee on Money, Foreign Exchange and Government Securities, RBI, June 2007 to December 2007.

Member of the Empowered Committee on using derivatives markets for hedging wheat procurement, Ministry of Finance, March 2007 to August 2008.

Member of the Technical Advisory Committee on Money, Foreign Exchange and Government Securities, RBI, June 2006 to June 2008.

Member of the Expert Advisory Group, ADB Technical Assistance project in India on Pension Reforms for the Unorganised Sector, July 2004.

Member of the Program Advisory Committee, NHAI, April 2003 to July 2003.Susan Thomas 5

Member of the Committee on assessment of state pension liabilities, RBI, April 2003 to September 2003.